### ISSUE TITLE
Reproduce experimental results

### ISSUE THREAD

**Issue by shopeth** [ChrisAllenMing/Mixup_for_UDA#3]
Hi,

Thank you for sharing the code. Interesting work!

I tried to reproduce the results for svhn -> mnist but the result obtained is lowered than source only. Could you please provide the data processing part for these two datasets? Currently I replaced the dataloaders by reading in the .mat files in original datasets. Not sure if this contributes to the performance issue.

**Comment by ChrisAllenMing** [comment]
Hi, 
I think the inferior performance is mainly ascribed to the dataset. You can download these two digits datasets from [this link](http://www.cs.umd.edu/~yogesh/datasets/digits.zip) and modify the '--dataroot' parameter to the corresponding path.

**Comment by shopeth** [comment]
Thank you for the response! I tried using these datasets and the result is better. The default parameters seem to yield better results. However, the best result averages to 86% in multiple runs and seeds. Any suggestions to improve it further?

**Comment by ChrisAllenMing** [comment]
I think this phenomenon is mainly caused by the lack of pseudo labeling scheme on target domain, and we apologize that, considering the correlation with one of our future work, we have to preclude the code for pseudo labeling in this repo. 
I suggest that you can refer to the pseudo labeling scheme in [this paper](https://openaccess.thecvf.com/content_cvpr_2018/CameraReady/1410.pdf) and re-implement it to further enhance model's performance.

**Comment by shopeth** [comment]
Okay. Thanks for the response.
